# Generated by Django 5.2.16 on 2026-08-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FlashcardDeck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("subject", models.CharField(max_length=50)),
                ("is_ai_generated", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FlashcardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("front", models.TextField()),
                ("back", models.TextField()),
                ("hint", models.TextField(blank=True, null=True)),
                ("visual_description", models.TextField(blank=True, null=True)),
                ("next_review", models.DateField(auto_now_add=True)),
                ("interval", models.PositiveIntegerField(default=1)),
                ("ease_factor", models.FloatField(default=2.5)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cards",
                        to="activities.flashcarddeck",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(max_length=50)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("score", models.FloatField(default=0.0)),
                (
                    "difficulty_used",
                    models.CharField(default="intermediate", max_length=20),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quizzes",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.TextField()),
                ("options", models.JSONField(default=list)),
                ("hint", models.TextField(blank=True, null=True)),
                ("explanation", models.TextField(blank=True, null=True)),
                ("correct_answer", models.CharField(max_length=150)),
                (
                    "user_answer",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("is_correct", models.BooleanField(default=False)),
                ("difficulty", models.CharField(default="intermediate", max_length=20)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="activities.quizsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        default="My Daily Learning Adventure", max_length=100
                    ),
                ),
                ("target_date", models.DateField()),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plans",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudyPlanItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=255)),
                ("is_done", models.BooleanField(default=False)),
                ("xp_reward", models.PositiveIntegerField(default=10)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="activities.studyplan",
                    ),
                ),
            ],
        ),
    ]
