# Generated by Django 5.2.16 on 2026-08-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="LearningJourneyNode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        choices=[
                            ("math", "Mathematics"),
                            ("science", "Science & Space"),
                            ("english", "English & Stories"),
                            ("coding", "Code Adventures"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("description", models.TextField()),
                ("order", models.PositiveIntegerField(default=1)),
                (
                    "difficulty_level",
                    models.CharField(default="intermediate", max_length=20),
                ),
                ("xp_reward", models.PositiveIntegerField(default=20)),
                ("content_data", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["subject", "order"],
            },
        ),
        migrations.CreateModel(
            name="AIConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("subject", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "title",
                    models.CharField(default="New Chat with Buddy", max_length=100),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIConversationMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender",
                    models.CharField(
                        choices=[("child", "Child"), ("ai", "AI Buddy")], max_length=10
                    ),
                ),
                ("text", models.TextField()),
                ("visual_explanations", models.JSONField(blank=True, default=dict)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="tutor.aiconversationsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LearningMemory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100)),
                ("value", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("interest", "Child's Interest"),
                            ("struggle", "Struggling Concept"),
                            ("preference", "Teaching Style Preference"),
                            ("fact", "Personal Fact"),
                        ],
                        default="interest",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memories",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "key")},
            },
        ),
        migrations.CreateModel(
            name="UserJourneyProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("locked", "Locked"),
                            ("unlocked", "Unlocked"),
                            ("completed", "Completed"),
                        ],
                        default="locked",
                        max_length=15,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "node",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="tutor.learningjourneynode",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="journey_progress",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "node")},
            },
        ),
    ]
