# Generated by Django 5.2.16 on 2026-08-01 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learnerprofile",
            name="selected_theme",
            field=models.CharField(default="theme-light", max_length=50),
        ),
    ]
