# Generated by Django 5.2.16 on 2026-08-01 16:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RewardItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("cost_coins", models.PositiveIntegerField(default=50)),
                (
                    "item_type",
                    models.CharField(
                        choices=[
                            ("avatar", "Avatar Profile Picture"),
                            ("theme", "Dashboard Color Theme"),
                            ("badge", "Special Badge Frame"),
                        ],
                        default="avatar",
                        max_length=20,
                    ),
                ),
                ("asset_name", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=150)),
                ("message", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("streak", "Streak Fire Update 🔥"),
                            ("reward", "Reward Unlocked 🎉"),
                            ("achievement", "Achievement Earned 🏆"),
                            ("system", "System Message 📣"),
                        ],
                        default="system",
                        max_length=20,
                    ),
                ),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserAchievement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("badge_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon_class", models.CharField(default="fa-trophy", max_length=50)),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="achievements",
                        to="accounts.learnerprofile",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "badge_name")},
            },
        ),
        migrations.CreateModel(
            name="UserRewardUnlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unlocked_at", models.DateTimeField(auto_now_add=True)),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unlocked_rewards",
                        to="accounts.learnerprofile",
                    ),
                ),
                (
                    "reward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="gamification.rewarditem",
                    ),
                ),
            ],
            options={
                "unique_together": {("profile", "reward")},
            },
        ),
    ]
